### ISSUE TITLE
Someone is selling your code

### ISSUE THREAD

**Issue by vswarte** [jdscodelab/EpicGamesLauncherUI#2]
Seems someone took your code and started licensing it as his own with some scuffed additions. He's sold derivative code to a bunch of youtubers as a whitelabeled product claiming "he wrote it".
https://github.com/Pear0533/ZModLauncher

**Comment by vswarte** [comment]
https://github.com/jdscodelab/EpicGamesLauncherUI/blob/main/EpicGamesLauncher.csproj#L7 https://github.com/Pear0533/ZModLauncher/blob/f438b454209e3f75ab5338bc814029f0f40875f6/ZModLauncher.csproj#L7

The project ID matches 1-to-1, I know he's been selling this code to people as well as go as far as copyright striking people on youtube over even showing imagery of this launcher.

**Comment by vswarte** [comment]
Offending repository went down real fast 🤡. He's still charging for it under the name "Rocket Hub Launcher": https://www.patreon.com/theonlypear.
![image](https://github.com/jdscodelab/EpicGamesLauncherUI/assets/6827387/b9c3db75-2a99-4cfb-a6d2-894450c7bce2)

**Comment by Pear0533** [comment]
@vswarte So you're saying that if I spent my own valuable time to watch these three tutorial videos (https://www.youtube.com/watch?v=WNjaFAfHFWg, https://www.youtube.com/watch?v=TtX47SlAFAM, https://www.youtube.com/watch?v=_jydqgGuBDo) and follow along with them to create my own launcher (with an entire implemented backend that isn't even shown in tutorial), then by the time I am done it I can't do anything with that source code?

_If_ the project GUIDs _were never the same_, and my project was a _completely new WPF project started from scratch_, would it still be the same situation? If I _WROTE_ the code myself _as I watched the tutorials_, I can't claim it as mine, even though there would be _undeniable_ differences in the amount of padding between UI elements, style appearances, etc. as a result?

**Comment by vswarte** [comment]
~~If you did as you describe it now the GUID's wouldn't have matched up~~ The project ID does indeed seem to be replicable but the solution GUID isn't. "A4876EC8-707B-4EE-B7C2-4903575EBC4"

**Comment by Pear0533** [comment]
By that very definition, that means _anyone_ watching a YouTube tutorial on how to create a user interface or anything else dealing with software in which the original tutorial repository in question doesn't have a license, they can't do anything with code they may have written themselves by following along with the tutorial? I'm not saying I followed the tutorial, I didn't, but I would like to know where boundaries can be crossed here.

What if it was a generic tutorial that described a simple concept in basic UI/backend design, and there was a repo for that with no license? Wouldn't we eventually get to the point where copyright can't necessarily be applied anymore because the code is so abstract and so common that it wouldn't make sense?

**Comment by Pear0533** [comment]
> If you did as you describe it now the GUID's wouldn't have matched up

Keep in mind that I had developed this launcher initially when I was working with GOE, so I unfortunately was too hypnotized by his greediness to do anything about it.

I recall GOE advising me to use this repository as a base, but clearly that isn't acceptable and I should've written it from scratch while following along with the tutorials during the creation of the project. I learned my lesson the hard way, it seems.

**Comment by Pear0533** [comment]
> Offending repository went down real fast 🤡. He's still charging for it under the name "Rocket Hub Launcher": https://www.patreon.com/theonlypear. ![image](https://user-images.githubusercontent.com/6827387/258001174-b9c3db75-2a99-4cfb-a6d2-894450c7bce2.png)

Also, I am not charging for it at all, it's completely free, what are you talking about? The only reason it appeared on my Patreon a few times is because I was updating my patrons on what was coming to RML, there's no early access for RML whatsoever. I would never charge for it because I am hoping to eventually see other modding communities adopt it for their purposes, for free. I literally have a Discord server centered around it: https://discord.gg/rAqAyXMPS8.

**Comment by vswarte** [comment]
You sold this launcher in white-labeled form to at least two people, most likely more

**Comment by Pear0533** [comment]
> You sold this launcher in white-labeled form to at least two people, most likely more

I actually never "sold" it at all. I was paid by GOE to create the launcher and I gave it to him and two other people, but I never got paid for it once I left his team. That's why I went out of my way to make a free alternative, and to keep it updated by improving various aspects of it and picking up where I had left off.

**Comment by Pear0533** [comment]
Why else would I have left the team? If he had paid me, I likely would've stayed to help develop it more while I was still working with his team. But that never happened.

And I am always going to keep RML free, because no one deserves to have to pay for mods, or, rather, accessibility for mods. I find it absolutely ridiculous, just as much as you or anyone else does. That's the whole point of RML. If you don't believe me, just join my Discord server and see for yourself. I even hosted a live presentation covering its new features: https://www.youtube.com/watch?v=w5mOlE7yZB8.

**Comment by vswarte** [comment]
![image](https://github.com/jdscodelab/EpicGamesLauncherUI/assets/6827387/d1a337d8-c643-4780-8add-6f599f518471)
???

**Comment by Pear0533** [comment]
> ![image](https://user-images.githubusercontent.com/6827387/258006632-d1a337d8-c643-4780-8add-6f599f518471.png) ???

Yeah, I was going to be paid for it. I never was though. I was never going to facilitate the payment either, GOE was going to do that.

**Comment by Pear0533** [comment]
> 

And like I said, if you join my Discord server and go to the rules channel, you can see the installer for RML as clear as day

**Comment by vswarte** [comment]
The 1EUR/month discord server? 🤡

**Comment by Pear0533** [comment]
> The 1EUR/month discord server? 🤡

???

Literally, what? I do not charge people anything for RML.

**Comment by Pear0533** [comment]
And the only reason my Patreon exists is for people to donate money if they so choose, which provides them access to early access versions of PUBLIC tools I have already released. This _does not_ include RML. Why would people donate to my Patreon to get RML? They literally can't, the only place you can get it is from my Discord server or Nexus Mods, on the ELDEN RING Dark Moon install page: [](https://www.nexusmods.com/eldenring/mods/2604?tab=files)

**Comment by Pear0533** [comment]
I would please ask that you simply close this issue. I have not sold (because I was never paid for it by GOE) my launcher to anyone, nor will I ever sell it to anyone, as I will be keeping RML free for as long as it lives. If you have any reasons to object against my claims, then please share them. Otherwise, please close this issue, as it is annoying to have my email filled up with this non-sense.

**Comment by vswarte** [comment]
At the end of the day you licensed code that wasn't yours then immediately pulled the repo and claim you did nothing wrong. I'm confused as hell about what you truly think about this situation.

**Comment by vswarte** [comment]
I would love to say this is the first time you did something like this 🤡. This man feeds off of clout gained merely by theft.

**Comment by vswarte** [comment]
Not to mention this kinda talk where you claim you (re)wrote everything from scratch (as always)

![image](https://github.com/jdscodelab/EpicGamesLauncherUI/assets/6827387/f88e96e5-fb0a-46a2-a2cf-98e87b77e757)

**Comment by Pear0533** [comment]
> At the end of the day you licensed code that wasn't yours then immediately pulled the repo and claim you did nothing wrong. I'm confused as hell about what you truly think about this situation.

The license was intended to cover the backend code and some of the user interface code that I wrote for the launcher. Unfortunately, I do not know of any way to explicitly separate the licensing for that from the rest of the code written by JD. If you can tell me any way of doing this, I would really appreciate it because I would like to give credit to him where it is due.

I would like to do anything I can to make this right. I guess the easiest thing to do would firstly be to remove the license, since I don't think there's any way I can delineate ownership of my code versus the code JD wrote in licensing terms.

**Comment by Pear0533** [comment]
> I would love to say this is the first time you did something like this 🤡. This man feeds off of clout gained merely by theft.

I am baffled that you have the audacity to say this. I do not "feed off of clout", I do not care about that. I care about making well-made tools that will assist modding communities for the greater good. Yes, I had engaged in theft of code before because I was still working with GOE at the time, and I had no choice in order to receive my fair pay from him. I didn't want to do it, but it's how it was.

I was also underage, so no formal contracts could be established at all with the people who owned some of the code we ended up using for the creation of certain tools, like the launcher. Establishing a private contract with JD would be possible right now as I am no longer underage: and this is legally acceptable by the way, but I would have to get a lawyer involved. Unfortunately I do not have the means to do so at the moment, but I would be willing to do so in the future if it means maintaining the integrity of Rocket Mod Launcher.

**Comment by Pear0533** [comment]
> Not to mention this kinda talk where you claim you (re)wrote everything from scratch (as always)
> 
> ![image](https://user-images.githubusercontent.com/6827387/258017786-f88e96e5-fb0a-46a2-a2cf-98e87b77e757.png)

Not entirely sure why I referenced the launcher here, you got me on that one. I will accept that I made a mistake there in terms of viewing the launcher as completely "re-written" from scratch. I take full responsibility for that statement.

**Comment by Pear0533** [comment]
> > Not to mention this kinda talk where you claim you (re)wrote everything from scratch (as always)
> > ![image](https://user-images.githubusercontent.com/6827387/258017786-f88e96e5-fb0a-46a2-a2cf-98e87b77e757.png)
> 
> Not entirely sure why I referenced the launcher here, you got me on that one. I will accept that I made a mistake there in terms of viewing the launcher as completely "re-written" from scratch. I take full responsibility for that statement.

GPARAM Studio, by the way, was completely built from the ground up. Take a look at the source repository. It does use some open-source interactive control libraries and of course, SoulsFormats.

**Comment by Seilock** [comment]
> > At the end of the day you licensed code that wasn't yours then immediately pulled the repo and claim you did nothing wrong. I'm confused as hell about what you truly think about this situation.
> 
> The license was intended to cover the backend code and some of the user interface code that I wrote for the launcher. Unfortunately, I do not know of any way to explicitly separate the licensing for that from the rest of the code written by JD. If you can tell me any way of doing this, I would really appreciate it because I would like to give credit to him where it is due.
> 
> I would like to do anything I can to make this right. I guess the easiest thing to do would firstly be to remove the license, since I don't think there's any way I can delineate ownership of my code versus the code JD wrote in licensing terms.

The code you have used is not licensed, you have no right to use it even if you figure out how to license only your portion.

**Comment by vswarte** [comment]
![image](https://github.com/jdscodelab/EpicGamesLauncherUI/assets/6827387/0c8abf85-83c7-4c15-b241-8d06ae44de74)
This is also pretty funny, the intention was there clearly

**Comment by vswarte** [comment]
All comments got wiped by @Pear0533 at this point so I'm closing this issue as to not further disturb the author of this project, may it live on in the google results for ever.

To close this all off: my main concern was him licensing code as his own that he never owned as he's done a few times before. I tried keeping it on his repository but he just removed all of it to avoid losing face. He gave word that he'll rewrite all of it but I sincerely doubt it, he will most likely continue selling "his" launcher as whitelabel and taking full credit for it.

To @jdscodelab: sincerely sorry you got wrapped up in this.
